theme: minima

title: My first blog site
author: Arielle O.
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is just for practice. I want to gain a better understanding of Github and it's capabilities.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
